
java_JAVA = Dataman.java DatamanComms.java DatamanErrVal.java \
	DatamanField.java DatamanFileDesc.java DatamanFunc.java \
	DatamanIndexFile.java DatamanIndex.java DatamanIndexSave.java \
	DatamanKey.java DatamanRecDesc.java DatamanRecord.java \
	DatamanRuntimeException.java

EXTRA_DIST = $(java_JAVA)

JAVAC = javac

JAVAROOT = ../

JAVACFLAGS = -classpath ./

CLEANFILES = $(JAVAROOT)Dataman/*.class

javadir = /usr/local/java/Dataman
